### ISSUE TITLE
Patient Reported Drugs/Conditions

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#25] opened 2018-05-07 19:12 UTC
TYPE | NOTES
-- | --
ITEM | What should be done with patient reported drugs or conditions?
FORUM POST | http://forums.ohdsi.org/t/patient-reported-drugs-and-conditions/3152
SOLUTION | Patient reported data recommendation should land in the appropriate domain table (e.g. if a patient reports they had lymphoma it should land in the CONDITION_OCCURRENCE table.  These data should be strongly typed so that it easily known which records are patient reported.  Type concepts include <br>44814721-Patient reported<br>44818706-Patient reported device<br>44818704-Patient reported value<br>45905770-Patient Self-Reported Condition<br>44787730-Patient Self-Reported Medication<br>44786633 – numeric HRA values<br>44786634 – categorical HRA values
NEXT STEPS | Ask the CDM WG to add this to the FAQ https://github.com/OHDSI/CommonDataModel/wiki/Frequently-Asked-Questions

**Comment by chandryou** [comment] 2018-06-05 23:54
@ericaVoss , We've started to develop converting process of Patient Generated Health Data from Health Apps to CDM.

I released the sample data of a gentleman for 1 year: [sample raw data from iPhone through QS Acess app](https://1drv.ms/f/s!Aseo02iy8GQ-jfsCw04bqUJOzjWifw
) 
And I'm developing sample ETL  for this: [sample CDM for PGHD](https://1drv.ms/x/s!Aseo02iy8GQ-jfoprRu6XRP3V8enQw)

Ultimately, the PGHD data of third-party health application of IT companies will be combined with hospital's CDM for only patients with approval. 

I classified nine types of PGHD, which I'll start to convert first:

1.  Activity
-Steps
-Flight climbed
-Distance 
2. Nutrition
- Calorie intake (24hr/ breakfast, lunch, dinner)
- Nutrient intake
3. Sleep
- Sleep start datetime
- Sleep end datetime
- Sleep total minutes
- Minutes asleep
- Time to fall sleep
- Number of sleep periods
4. Body measurements
- Height
- Weight
- BMI
- Lean body
- Body fat
5. Vital signs
- Heart Rate
- Blood pressure
- Heart Rate Variability
6. Self-medication
- Insulin
7. Self-laboratory measurement
- gluclse
8. Self-report
9. Mindfulness

**Comment by PRijnbeek** [comment] 2018-06-15 11:33
We agree with the proposal

**Comment by ericaVoss** [comment] 2018-07-09 16:18
In addition to this ticket we added ATLAS:
https://github.com/OHDSI/Atlas/issues/753

**Comment by vojtechhuser** [comment] 2019-05-08 19:50
I don't see it in the FAQ. It should go into conventions. (and the problem is that it needs to be in both CONDITION_OCCURRENCE and in DRUG_EXPOSURE. (identical convention). Do we have a precedence solution for it?  (maybe FAQ is the solution but it may not be prominent enough for ETLers.

**Comment by MelaniePhilofsky** [comment] 2023-07-05 16:33
Closing the issue. The Type Concept domain has been updated with a [standard concept_ids](https://athena.ohdsi.org/search-terms/terms?domain=Type+Concept&standardConcept=Standard&page=1&pageSize=15&query=patient) for patient reported data.

**Closed by MelaniePhilofsky** 2023-07-05 16:33 UTC
Labels: PRIORITY MEDIUM
